export * from "./components/navMenue";
export * from "./components/dashboard";
export * from "./components/serviceCard"
export * from "./components/order";
export * from "./components/layoutpanel"
export * from "./components/headerflightticket"
export * from "./components/detailssection"
export * from "./components/passengerdetails"
export * from "./components/contactinfo"
export * from "./components/passengersinfo"
export * from "./components/passengersloading"
